baseURL = "https://derossimolina.github.io/"
languageCode = "pt-BR"
title = "J. de Rossi Molina, PhD candidate in Administration | Researching about Complexity and AI for Public Management"
theme = "nous"
paginate = 10

[params]
  description  = "Notas, ensaios e pesquisa"
  shortTitle   = "derossimolina"
  homeTitle    = "derossimolina"
  homeContent  = "Notas e ensaios sobre ciência, política e sistemas complexos."

[menu]
  [[menu.main]]
    name   = "posts"
    url    = "/posts/"
    weight = 10
  [[menu.main]]
    name   = "pesquisas"
    url    = "/pesquisas/"
    weight = 20
  [[menu.main]]
    name   = "publicações"
    url    = "/publicacoes/"
    weight = 30
  [[menu.main]]
    name   = "atividades"
    url    = "/atividades/"
    weight = 40
  [[menu.main]]
    name   = "sobre"
    url    = "/sobre/"
    weight = 50

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
